"""add defect groups and types

Revision ID: 503f387ba323
Revises: c3d4e5f6a7b8
Create Date: 2026-09-01 19:14:56.488394+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# Revision identifiers used by Alembic.
revision: str = "503f387ba323"
down_revision: str | Sequence[str] | None = "c3d4e5f6a7b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema changes for this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "defect_groups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_defect_groups")),
        sa.UniqueConstraint("code", name=op.f("uq_defect_groups_code")),
    )
    op.create_index("ix_defect_groups_archived_at", "defect_groups", ["archived_at"], unique=False)
    op.create_table(
        "defect_types",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("possible_cause", sa.Text(), nullable=True),
        sa.Column("engineer_action", sa.Text(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["defect_groups.id"],
            name=op.f("fk_defect_types_group_id_defect_groups"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_defect_types")),
        sa.UniqueConstraint("code", name=op.f("uq_defect_types_code")),
    )
    op.create_index("ix_defect_types_archived_at", "defect_types", ["archived_at"], unique=False)
    op.create_index("ix_defect_types_group_id", "defect_types", ["group_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the schema changes for this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_defect_types_group_id", table_name="defect_types")
    op.drop_index("ix_defect_types_archived_at", table_name="defect_types")
    op.drop_table("defect_types")
    op.drop_index("ix_defect_groups_archived_at", table_name="defect_groups")
    op.drop_table("defect_groups")
    # ### end Alembic commands ###
