name: web-app

x-default-logging: &default-logging
  driver: local
  options:
    max-size: "10m"
    max-file: "3"

x-backend-environment: &backend-environment
  BACKEND_POSTGRES_HOST: postgres
  BACKEND_POSTGRES_PORT: 5432
  BACKEND_POSTGRES_USER: ${POSTGRES_USER:-postgres}
  BACKEND_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-}
  BACKEND_POSTGRES_DB: ${POSTGRES_DB:-postgres}

  BACKEND_REDIS_HOST: redis
  BACKEND_REDIS_PORT: 6379
  BACKEND_REDIS_DB: ${BACKEND_REDIS_DB:-0}

x-backend-image: &backend-image
  image: "web-app-backend:${TAG:-dev}"
  build:
    context: ./apps/backend
    dockerfile: Dockerfile
    args:
      BACKEND_VERSION: ${BACKEND_VERSION:-dev}

services:

  postgres:
    image: postgres:17-alpine
    logging: *default-logging
    restart: unless-stopped
    volumes:
      - app-postgres-data:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
      start_interval: 5s

  redis:
    image: redis:8-alpine
    logging: *default-logging
    restart: unless-stopped
    volumes:
      - app-redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "-e", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
      start_interval: 5s

  prestart:
    <<: *backend-image
    networks:
      - default
    depends_on:
      postgres:
        condition: service_healthy
    command: ["bash", "scripts/prestart.sh"]
    environment:
      <<: *backend-environment

  backend:
    <<: *backend-image
    logging: *default-logging
    init: true
    networks:
      - default
    depends_on:
      redis:
        condition: service_healthy
      prestart:
        condition: service_completed_successfully
    command: ["bash", "scripts/start.sh"]
    environment:
      <<: *backend-environment
    healthcheck:
      test: ["CMD", "python", "scripts/healthcheck.py"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 20s
      start_interval: 5s

volumes:
  app-postgres-data:
  app-redis-data:

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: "1400"
