CREATE ROLE kratos_migrator
    LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION
    PASSWORD :'migrator_password';

CREATE ROLE kratos_runtime
    LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION
    PASSWORD :'runtime_password';

CREATE DATABASE kratos OWNER kratos_migrator;
REVOKE ALL ON DATABASE kratos FROM PUBLIC;
GRANT CONNECT ON DATABASE kratos TO kratos_migrator, kratos_runtime;

\connect kratos

REVOKE ALL ON SCHEMA public FROM PUBLIC;
ALTER SCHEMA public OWNER TO kratos_migrator;
GRANT USAGE ON SCHEMA public TO kratos_runtime;

GRANT SELECT, INSERT, UPDATE, DELETE
    ON ALL TABLES IN SCHEMA public TO kratos_runtime;
GRANT USAGE, SELECT, UPDATE
    ON ALL SEQUENCES IN SCHEMA public TO kratos_runtime;

ALTER DEFAULT PRIVILEGES FOR ROLE kratos_migrator IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO kratos_runtime;
ALTER DEFAULT PRIVILEGES FOR ROLE kratos_migrator IN SCHEMA public
    GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO kratos_runtime;
