CREATE ROLE web_app_migrator
    LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION
    PASSWORD :'migrator_password';

CREATE ROLE web_app_runtime
    LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION
    PASSWORD :'runtime_password';

CREATE DATABASE web_app OWNER web_app_migrator;
REVOKE ALL ON DATABASE web_app FROM PUBLIC;
GRANT CONNECT ON DATABASE web_app TO web_app_migrator, web_app_runtime;

\connect web_app

REVOKE ALL ON SCHEMA public FROM PUBLIC;
ALTER SCHEMA public OWNER TO web_app_migrator;
GRANT USAGE ON SCHEMA public TO web_app_runtime;

GRANT SELECT, INSERT, UPDATE, DELETE
    ON ALL TABLES IN SCHEMA public TO web_app_runtime;
GRANT USAGE, SELECT, UPDATE
    ON ALL SEQUENCES IN SCHEMA public TO web_app_runtime;

ALTER DEFAULT PRIVILEGES FOR ROLE web_app_migrator IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO web_app_runtime;
ALTER DEFAULT PRIVILEGES FOR ROLE web_app_migrator IN SCHEMA public
    GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO web_app_runtime;
