CREATE ROLE hydra_migrator
    LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION
    PASSWORD :'migrator_password';

CREATE ROLE hydra_runtime
    LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION
    PASSWORD :'runtime_password';

CREATE DATABASE hydra OWNER hydra_migrator;
REVOKE ALL ON DATABASE hydra FROM PUBLIC;
GRANT CONNECT ON DATABASE hydra TO hydra_migrator, hydra_runtime;

\connect hydra

REVOKE ALL ON SCHEMA public FROM PUBLIC;
ALTER SCHEMA public OWNER TO hydra_migrator;
GRANT USAGE ON SCHEMA public TO hydra_runtime;

GRANT SELECT, INSERT, UPDATE, DELETE
    ON ALL TABLES IN SCHEMA public TO hydra_runtime;
GRANT USAGE, SELECT, UPDATE
    ON ALL SEQUENCES IN SCHEMA public TO hydra_runtime;

ALTER DEFAULT PRIVILEGES FOR ROLE hydra_migrator IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO hydra_runtime;
ALTER DEFAULT PRIVILEGES FOR ROLE hydra_migrator IN SCHEMA public
    GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO hydra_runtime;
