services:
  traefik:
    ports:
      - "80:80"
    command:
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--ping=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik-public"
      - "--providers.docker.constraints=Label(`traefik.constraint-label`,`traefik-public`)"
      - "--entrypoints.http.address=:80"
      - "--log.level=DEBUG"
      - "--log.format=common"
      - "--accesslog=true"
      - "--accesslog.addinternals=true"
      - "--accesslog.format=common"
