from typing import Literal, Protocol
from uuid import UUID

from app.shared.security import Identity


class UserIdentityProviderPort(Protocol):
    """Narrow application port for the Kratos Admin operations used by users."""

    async def create_identity(
        self,
        *,
        login: str,
        password: str,
        active: bool,
        user_id: UUID,
        provisioning_kind: Literal["standard", "bootstrap"] = "standard",
    ) -> Identity: ...
    async def get_identity_by_external_id(self, user_id: UUID) -> Identity: ...
    async def get_identity(self, identity_id: UUID) -> Identity: ...
    async def update_login(self, identity_id: UUID, *, login: str) -> Identity: ...
    async def set_password(self, identity_id: UUID, *, password: str) -> None: ...
    async def set_active(self, identity_id: UUID, *, active: bool) -> Identity: ...
    async def revoke_all_sessions(self, identity_id: UUID) -> None: ...
    async def delete_identity(self, identity_id: UUID) -> None: ...
    async def list_identities(self, *, page_size: int) -> list[Identity]: ...
