services:
  prestart:
    image: "otk-app-backend:${BACKEND_TAG:?BACKEND_TAG is required}"
    environment:
      LITESTAR_DEBUG: "false"
      BACKEND_LOG_JSON: "true"

  api:
    image: "otk-app-backend:${BACKEND_TAG:?BACKEND_TAG is required}"
    restart: unless-stopped
    labels:
      traefik.http.routers.api.entrypoints: https
      traefik.http.routers.api.tls: "true"
      traefik.http.routers.api.tls.certresolver: letsencrypt
    environment:
      LITESTAR_DEBUG: "false"
      BACKEND_LOG_JSON: "true"

  worker:
    image: "otk-app-backend:${BACKEND_TAG:?BACKEND_TAG is required}"
    restart: unless-stopped
    environment:
      BACKEND_LOG_JSON: "true"
