"""Production API schemas."""

from app.domain.production.schemas._batch import (
    Batch,
    BatchCreate,
    BatchKgPrefix,
    BatchKgVersion,
    BatchMulticastGroup,
    BatchProductionOrder,
    BatchProductionOrderAssignment,
    BatchUpdate,
    DevEuiRange,
    UserSummary,
)
from app.domain.production.schemas._batch_receipt import (
    BatchReceipt,
    BatchReceiptCreate,
    BatchReceiptUpdate,
    BatchReceiptVoid,
)
from app.domain.production.schemas._batch_shipment import (
    BatchShipment,
    BatchShipmentComplete,
    BatchShipmentCreate,
    BatchShipmentItem,
    BatchShipmentUnitRejected,
    BatchShipmentUnitRejection,
    BatchShipmentUnitsAdd,
    BatchShipmentUnitsAdded,
    BatchShipmentUpdate,
    BatchShipmentVoid,
)
from app.domain.production.schemas._kg_prefix import (
    KgPrefix,
    KgPrefixCreate,
    KgPrefixUpdate,
)
from app.domain.production.schemas._kg_unit import (
    KgOtkFilter,
    KgTimelineEvent,
    KgTimelineEventKind,
    KgTimelineSession,
    KgTimelineShipment,
    KgUnit,
    KgUnitAbp10Credentials,
    KgUnitAbp11Credentials,
    KgUnitBatch,
    KgUnitCredentials,
    KgUnitOtaa10Credentials,
    KgUnitOtaa11Credentials,
    KgUnitPak,
    KgUnitRunningOtk,
    KgUnitShipment,
)
from app.domain.production.schemas._kg_version import (
    KgVersion,
    KgVersionCreate,
    KgVersionUpdate,
)
from app.domain.production.schemas._multicast_group import (
    MulticastGroup,
    MulticastGroupCreate,
    MulticastGroupKeys,
    MulticastGroupUpdate,
)
from app.domain.production.schemas._packing import (
    PackingBlocker,
    PackingUnit,
    PackingUnitBatch,
)
from app.domain.production.schemas._production_order import (
    ProductionOrder,
    ProductionOrderCreate,
    ProductionOrderUpdate,
)

__all__ = (
    "Batch",
    "BatchCreate",
    "BatchKgPrefix",
    "BatchKgVersion",
    "BatchMulticastGroup",
    "BatchProductionOrder",
    "BatchProductionOrderAssignment",
    "BatchReceipt",
    "BatchReceiptCreate",
    "BatchReceiptUpdate",
    "BatchReceiptVoid",
    "BatchShipment",
    "BatchShipmentComplete",
    "BatchShipmentCreate",
    "BatchShipmentItem",
    "BatchShipmentUnitRejected",
    "BatchShipmentUnitRejection",
    "BatchShipmentUnitsAdd",
    "BatchShipmentUnitsAdded",
    "BatchShipmentUpdate",
    "BatchShipmentVoid",
    "BatchUpdate",
    "DevEuiRange",
    "KgOtkFilter",
    "KgPrefix",
    "KgPrefixCreate",
    "KgPrefixUpdate",
    "KgTimelineEvent",
    "KgTimelineEventKind",
    "KgTimelineSession",
    "KgTimelineShipment",
    "KgUnit",
    "KgUnitAbp10Credentials",
    "KgUnitAbp11Credentials",
    "KgUnitBatch",
    "KgUnitCredentials",
    "KgUnitOtaa10Credentials",
    "KgUnitOtaa11Credentials",
    "KgUnitPak",
    "KgUnitRunningOtk",
    "KgUnitShipment",
    "KgVersion",
    "KgVersionCreate",
    "KgVersionUpdate",
    "MulticastGroup",
    "MulticastGroupCreate",
    "MulticastGroupKeys",
    "MulticastGroupUpdate",
    "PackingBlocker",
    "PackingUnit",
    "PackingUnitBatch",
    "ProductionOrder",
    "ProductionOrderCreate",
    "ProductionOrderUpdate",
    "UserSummary",
)
